// Turns balance results into a Markdown report.
import { getEncounterConfig } from '../../shared/combat/encounters.js';

const pct = (value) => `${Math.round(value * 100)}%`;
const signed = (value) => `${value >= 0 ? '+' : ''}${value.toFixed(2)}`;
const tierName = (tier) => (tier === 'ult' ? 'Ultimate' : `Level ${tier}`);

export function renderPartySizes(partySizes) {
    const sizes = Object.keys(partySizes).sort((a, b) => a - b);
    const fights = partySizes[sizes[0]].fights.map(row => row.encounterIndex);
    const lines = [];
    lines.push(`| Fight | Type | ${sizes.map(size => `${size}P`).join(' | ')} |`);
    lines.push(`|---|---|${sizes.map(() => '---').join('|')}|`);
    for (const index of fights) {
        const cells = sizes.map(size => pct(partySizes[size].fights.find(row => row.encounterIndex === index).winRate));
        lines.push(`| ${index + 1} | ${getEncounterConfig(index).combatType} | ${cells.join(' | ')} |`);
    }
    lines.push(`| **Whole campaign** | | ${sizes.map(size => `**${(partySizes[size].campaign * 100).toFixed(partySizes[size].campaign < 0.01 ? 2 : 0)}%**`).join(' | ')} |`);
    // How long fights last: each unit's turn counts once per round.
    const averageRounds = (size) => partySizes[size].fights.reduce((total, row) => total + row.rounds, 0) / partySizes[size].fights.length;
    lines.push(`| Average rounds per fight | | ${sizes.map(size => averageRounds(size).toFixed(1)).join(' | ')} |`);
    return lines.join('\n');
}

export function renderAbilities(abilities) {
    const sections = [];
    for (const { role, tier, rows } of abilities) {
        const lines = [`#### ${role} - ${tierName(tier)}`, '', '| Ability | Edge vs slot average | Win rate | Uses per fight |', '|---|---|---|---|'];
        for (const row of rows) {
            lines.push(`| ${row.name} | ${signed(row.edge)} ± ${row.edgeError.toFixed(2)} | ${pct(row.winRate)} | ${row.usesPerFight.toFixed(1)} |`);
        }
        sections.push(lines.join('\n'));
    }
    return sections.join('\n\n');
}

export function renderReport(data) {
    const parts = [`<!-- generated by Server/scripts/balance.js on ${data.createdAt} (${data.policy} bots, ${data.seconds}s) -->`];
    if (data.partySizes) {
        parts.push(`### Win rate per fight by party size (${data.samples} random parties each)\n\n${renderPartySizes(data.partySizes)}`);
    }
    if (data.abilities) {
        parts.push(`### Abilities compared within their slot (${data.abilitySamples} paired scenarios each)\n\n${renderAbilities(data.abilities)}`);
    }
    return parts.join('\n\n') + '\n';
}
